### ISSUE TITLE
Add chromium and lutris to the bentoo version 

### ISSUE THREAD

**Issue by DraGiuS** [lucascouts/bentoo-cfg#2]

**Comment by lucascouts** [comment]
That need to be requested on Bentoo overlay.

here is just the configuration, not ebuilds

https://github.com/lucascouts/bentoo

**Comment by DraGiuS** [comment]
I wanted to say, add them to the default set of packages

**Comment by lucascouts** [comment]
Chomium take few hours to compile, so Firefox is the default browser installed and lutris is already added, the stage version will be available tomorrow.

the Chromium and the others packages out of the default world will be added in a secondary binhost.

**Comment by DraGiuS** [comment]
Thanks.
