### ISSUE TITLE
How to install the stage4 ?

### ISSUE THREAD

**Issue by DraGiuS** [lucascouts/bentoo-cfg#3]

**Comment by DraGiuS** [comment]
I mean how to install it with the original wiki writted by funtoo

**Comment by lucascouts** [comment]
To install just follow the Funtoo installation steps and replace the downloaded stage3 with the Bentoo Stage4.

https://www.funtoo.org/install

**Comment by lucascouts** [comment]
Join on the telegram group, I can help you directly threre. https://t.me/joinchat/DG0l5Rez0MRt4p2GHnNohQ
